/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.demo_mini_10;

import java.io.File;

import org.apache.catalina.Context;
import org.apache.catalina.core.StandardContext;
import org.apache.catalina.startup.Tomcat;

public class Main {
    public void run() {
        Tomcat tomcat = new Tomcat();
        tomcat.setPort(8080);
        tomcat.getConnector();
        String webAppPath = new File("src/main/webapp").getAbsolutePath();
        new File(webAppPath).mkdirs();
        
        Context context = tomcat.addWebapp("", webAppPath);

        // CHỈ CẦN DÒNG NÀY ĐỂ SPRING CHẠY ĐƯỢC
        if (context instanceof StandardContext standardContext) {
            standardContext.setParentClassLoader(Thread.currentThread().getContextClassLoader());
        }

        try {
            tomcat.start();
            System.out.println("Application started at: http://localhost:8080");
            tomcat.getServer().await();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        new Main().run();
    }
}
